# Fun Basics

In [3]:
3+7

10

In [4]:
print("hello")

hello


In [5]:
name= "Avi"
age= 21

In [6]:
# This is a comment. It will not run
# You can echovalues without using print in this notebook

In [7]:
name

'Avi'

# Variables and values

In [9]:
# Variables can be used in calculations
print(age)
age = age + 3
print (age)

21
24


In [10]:
# Order of Operations matters!
first = 1
second = first * 5
first = 2
print (first)
print (second)

2
5


In [11]:
# Values have types. Types affect what you can do with them.
print (5-3)
#print ("hello"-"h")

2


In [12]:
print(len("hello"))
#print(len(6))

5


In [13]:
print (5 // 3)
print (5 / 3)
print (5 % 3)


1
1.6666666666666667
2


# Getting Help

In [15]:
# Rounding numbers is built in
round (3.14159)

3

In [16]:
round(3.14159,2)

3.14

In [17]:
round(3.14159, ndigits=2)

3.14

In [18]:
# All functions return a new value
rounded_pi=round(3.14159,2)
print(rounded_pi)

3.14


In [19]:
radiance=1.0
radiance=max(2.1,2.0+min(radiance,1.1*radiance-0.5))
print(radiance)

2.6


In [20]:
# Break down these operations
radiance = 1.0
min_arg_2= 1.1 * radiance -0.5
print("Min arg2:", min_arg_2)

min_result = min(radiance, min_arg_2)
print("Min result:",min_result)

radiance=max(2.1,2.0 + min_result)
print(radiance)

Min arg2: 0.6000000000000001
Min result: 0.6000000000000001
2.6


# A Brief Interlude with Git

# Libraries

In [23]:
import math

In [24]:
math.pi

3.141592653589793

In [25]:
print(math.cos(math.pi))

-1.0


In [26]:
# get complete help with help ()
# help(math)
# Get a list of options with dir()
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'sumprod', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


# List

In [28]:
# A list is an ordered collection of stuff
fruits = ["apple","banana","cherry","date","elderberry","fig"]

In [29]:
fruits

['apple', 'banana', 'cherry', 'date', 'elderberry', 'fig']

In [30]:
len(fruits)

6

In [31]:
# Lists are indeced by osition, counting from zero
# First item
print(fruits[0])

apple


In [32]:
# Get subsets by slicing the list
# Get the first 3 items
fruits[0:3]

['apple', 'banana', 'cherry']

In [33]:
# Get items by step
# Get the first five items, every other item
fruits[0:5:2]

['apple', 'cherry', 'elderberry']

# Examles

In [35]:
fruits[-1]
#fruits[20]
fruits[-3]

'date'

In [36]:
fruits[-1]

'fig'

In [37]:
#fruits[20]

fruits[-3:]

In [39]:
print(fruits)

['apple', 'banana', 'cherry', 'date', 'elderberry', 'fig']


# Adding stuff to lists

In [41]:
# Update a specific item
print(fruits)
fruits[0]= "apricot"

['apple', 'banana', 'cherry', 'date', 'elderberry', 'fig']


In [42]:
# Add new items to the list
fruits.append("grape")
print(fruits)

['apricot', 'banana', 'cherry', 'date', 'elderberry', 'fig', 'grape']


In [43]:
# Add items from a second list to the first list
more_fruits=["honeydew","imbe","jackfruit"]
print(more_fruits)
fruits.extend(more_fruits)
print(fruits)

['honeydew', 'imbe', 'jackfruit']
['apricot', 'banana', 'cherry', 'date', 'elderberry', 'fig', 'grape', 'honeydew', 'imbe', 'jackfruit']


In [44]:
# Many functions operate on collections
# Asessing our wide receiving corp
receiving_yards = [450,370,870,150]

mean_yards = sum(receiving_yards)/len(receiving_yards)
print(mean_yards)

460.0


# For loops

In [46]:
for fruit in fruits:
    print(fruit)

apricot
banana
cherry
date
elderberry
fig
grape
honeydew
imbe
jackfruit


In [47]:
# Code blocks can contain many statements
primes = [2, 3, 5]
for p in primes:
    squared = p**2
    cubed = p**3
    print(p, squared, cubed)

2 4 8
3 9 27
5 25 125


In [48]:
# Create a new collection from an existing collection
primes_squared=[]
for p in primes:
    primes_squared.append(p ** 2)

print(primes_squared)

[4, 9, 25]


In [49]:
total_length=0
for f in fruits:
    length_each= len(f)
    total_length = total_length+(length_each)
    print(total_length)

7
13
19
23
33
36
41
49
53
62


In [50]:
print(fruits)

['apricot', 'banana', 'cherry', 'date', 'elderberry', 'fig', 'grape', 'honeydew', 'imbe', 'jackfruit']


In [51]:
# Generator comprehension
sum(len(f) for f in fruits)

62

In [52]:
joined_fruits = "".join(fruits)
print(joined_fruits)
print(len(joined_fruits))

apricotbananacherrydateelderberryfiggrapehoneydewimbejackfruit
62


# Linear Algebra with NumPy


In [54]:
import numpy as np

In [55]:
# Create an array of random numbers
# Row, Column
m_rand = np.random.rand(3,4)
print(m_rand)

[[0.43114009 0.46295217 0.57154411 0.17356618]
 [0.40573571 0.60222742 0.88357133 0.72791316]
 [0.3642401  0.35683641 0.80440633 0.64163881]]


In [56]:
m_rand[0,0]

0.4311400930295838

In [57]:
# Row,Column
m_rand[0,1]

0.46295216930544014

In [58]:
# Arrays have a bunch of attributes associated with it
#shape of matrix
print(m_rand.shape)
#size of matrix
print(m_rand.size)
#number of dimensions
print(m_rand.ndim)

(3, 4)
12
2


In [59]:
# Linear algerbra with Numpy
# First Nine counting numbers
x = np.arange(9)
y = np.arange(9)
print(x)
print(y)

[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]


In [60]:
# Element-wise multiplication (operations are element-wise by default)
x*y

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

In [61]:
# Matrix-wise operations if you like (dot-product)
x @ y

204

In [62]:
# You can reshape arrays into different formations (Row, Column)
x1 = x.reshape(3,3)
x2 = x.reshape(9,1)
print(x)
print(x1)
print(x2)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


## Challenge 

1. Create a 3 x 3 array with the number 0-8
2. Multiply array by itself (elementwise)
3. Multiply the array by its transpose

In [64]:
x = np.arange(9)
x1= x.reshape(3,3)
print(x1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [65]:
# Use method chaining to do more work on one line 
demo = np.arange(9).reshape(3,3)
print(demo)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [66]:
demo*demo

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [67]:
# Get transpose, method 1
demo * demo.T

array([[ 0,  3, 12],
       [ 3, 16, 35],
       [12, 35, 64]])

In [68]:
# Get transpose, method 2
demo * np.transpose(demo)

array([[ 0,  3, 12],
       [ 3, 16, 35],
       [12, 35, 64]])

In [69]:
#demo / demo  (can't divide by zero)

# Working with Data in Pandas

In [71]:
import pandas as pd

In [72]:
# Import data files
data = pd.read_csv("gapminder_gdp_oceania.csv")
print(data)

       country  gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
0    Australia     10039.59564     10949.64959     12217.22686   
1  New Zealand     10556.57566     12247.39532     13175.67800   

   gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  \
0     14526.12465     16788.62948     18334.19751     19477.00928   
1     14463.91893     16046.03728     16233.71770     17632.41040   

   gdpPercap_1987  gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  \
0     21888.88903     23424.76683     26997.93657     30687.75473   
1     19007.19129     18363.32494     21050.41377     23189.80135   

   gdpPercap_2007  
0     34435.36744  
1     25185.00911  


In [73]:
# Print Nicely without using print
data

country  gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
0    Australia     10039.59564     10949.64959     12217.22686   
1  New Zealand     10556.57566     12247.39532     13175.67800   

   gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  \
0     14526.12465     16788.62948     18334.19751     19477.00928   
1     14463.91893     16046.03728     16233.71770     17632.41040   

   gdpPercap_1987  gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  \
0     21888.88903     23424.76683     26997.93657     30687.75473   
1     19007.19129     18363.32494     21050.41377     23189.80135   

   gdpPercap_2007  
0     34435.36744  
1     25185.00911

In [74]:
# Import csv and index by country name (all "countries" need to be unique to work)
data = pd.read_csv("gapminder_gdp_oceania.csv", index_col = "country")

In [75]:
data

gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
country                                                                       
Australia       10039.59564     10949.64959     12217.22686     14526.12465   
New Zealand     10556.57566     12247.39532     13175.67800     14463.91893   

             gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
country                                                                       
Australia       16788.62948     18334.19751     19477.00928     21888.88903   
New Zealand     16046.03728     16233.71770     17632.41040     19007.19129   

             gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007  
country                                                                      
Australia       23424.76683     26997.93657     30687.75473     34435.36744  
New Zealand     18363.32494     21050.41377     23189.80135     25185.00911

In [147]:
# Good advice about python 
import this

In [141]:
# Data frames have attributes
print(data.index)
print(data.columns)
print(data.shape)

Index(['Australia', 'New Zealand'], dtype='object', name='country')
Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
       'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
       'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007'],
      dtype='object')
(2, 12)


In [151]:
# Data frames can tell you about their content
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, Australia to New Zealand
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   gdpPercap_1952  2 non-null      float64
 1   gdpPercap_1957  2 non-null      float64
 2   gdpPercap_1962  2 non-null      float64
 3   gdpPercap_1967  2 non-null      float64
 4   gdpPercap_1972  2 non-null      float64
 5   gdpPercap_1977  2 non-null      float64
 6   gdpPercap_1982  2 non-null      float64
 7   gdpPercap_1987  2 non-null      float64
 8   gdpPercap_1992  2 non-null      float64
 9   gdpPercap_1997  2 non-null      float64
 10  gdpPercap_2002  2 non-null      float64
 11  gdpPercap_2007  2 non-null      float64
dtypes: float64(12)
memory usage: 208.0+ bytes


In [159]:
# Get descriptive statistics 
data.describe()

gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
count        2.000000        2.000000        2.000000        2.000000   
mean     10298.085650    11598.522455    12696.452430    14495.021790   
std        365.560078      917.644806      677.727301       43.986086   
min      10039.595640    10949.649590    12217.226860    14463.918930   
25%      10168.840645    11274.086022    12456.839645    14479.470360   
50%      10298.085650    11598.522455    12696.452430    14495.021790   
75%      10427.330655    11922.958888    12936.065215    14510.573220   
max      10556.575660    12247.395320    13175.678000    14526.124650   

       gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
count         2.00000        2.000000        2.000000        2.000000   
mean      16417.33338    17283.957605    18554.709840    20448.040160   
std         525.09198     1485.263517     1304.328377     2037.668013   
min       16046.03728    16233.717700    17632.410400    19007.191290   
25%       16231.68533    16758.837652    18093.560120    19727.615725   
50%       16417.33338    17283.957605    18554.709840    20448.040160   
75%       16602.98143    17809.077558    19015.859560    21168.464595   
max       16788.62948    18334.197510    19477.009280    21888.889030   

       gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007  
count        2.000000        2.000000        2.000000        2.000000  
mean     20894.045885    24024.175170    26938.778040    29810.188275  
std       3578.979883     4205.533703     5301.853680     6540.991104  
min      18363.324940    21050.413770    23189.801350    25185.009110  
25%      19628.685412    22537.294470    25064.289695    27497.598692  
50%      20894.045885    24024.175170    26938.778040    29810.188275  
75%      22159.406358    25511.055870    28813.266385    32122.777858  
max      23424.766830    26997.936570    30687.754730    34435.367440

In [161]:
# Get the first n rows
data.head(1)

gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
country                                                                     
Australia     10039.59564     10949.64959     12217.22686     14526.12465   

           gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
country                                                                     
Australia     16788.62948     18334.19751     19477.00928     21888.88903   

           gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007  
country                                                                    
Australia     23424.76683     26997.93657     30687.75473     34435.36744

In [169]:
#help(data.describe()) if looking for help

In [171]:
# Swap rows and columns to describe
data.T.describe()

country     Australia   New Zealand
count       12.000000     12.000000
mean     19980.595634  17262.622813
std       7815.405220   4409.009167
min      10039.595640  10556.575660
25%      13948.900203  14141.858697
50%      18905.603395  16933.064050
75%      24318.059265  19517.996910
max      34435.367440  25185.009110

# Subsetting Data

In [178]:
#Add data/file name to organize it
data=pd.read_csv("gapminder_gdp_europe.csv", index_col = "country")

In [181]:
data.head(3)

gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
country                                                                   
Albania     1601.056136     1942.284244     2312.888958     2760.196931   
Austria     6137.076492     8842.598030    10750.721110    12834.602400   
Belgium     8343.105127     9714.960623    10991.206760    13149.041190   

         gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
country                                                                   
Albania     3313.422188      3533.00391     3630.880722     3738.932735   
Austria    16661.625600     19749.42230    21597.083620    23687.826070   
Belgium    16672.143560     19117.97448    20979.845890    22525.563080   

         gdpPercap_1992  gdpPercap_1997  gdpPercap_2002  gdpPercap_2007  
country                                                                  
Albania     2497.437901     3193.054604     4604.211737     5937.029526  
Austria    27042.018680    29095.920660    32417.607690    36126.492700  
Belgium    25575.570690    27561.196630    30485.883750    33692.605080

In [191]:
# Get item by index location (dumb way to do it)
data.iloc[0,0]

1601.056136

In [193]:
# Get item by label
data.loc["Albania", "gdpPercap_1952"]

1601.056136

# A brief digression on string methods

In [196]:
# Standard python has string methods
# Capitalize
big_hello = "hello".title()
print(big_hello)

Hello


In [198]:
# What methods are available?
print(dir("hello"))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [200]:
print(data.columns)

Index(['gdpPercap_1952', 'gdpPercap_1957', 'gdpPercap_1962', 'gdpPercap_1967',
       'gdpPercap_1972', 'gdpPercap_1977', 'gdpPercap_1982', 'gdpPercap_1987',
       'gdpPercap_1992', 'gdpPercap_1997', 'gdpPercap_2002', 'gdpPercap_2007'],
      dtype='object')


In [202]:
# What string methods can I do to all the columns?
print(dir(data.columns.str))

['__annotations__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__frozen', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_data', '_doc_args', '_freeze', '_get_series_list', '_index', '_inferred_dtype', '_is_categorical', '_is_string', '_name', '_orig', '_parent', '_validate', '_wrap_result', 'capitalize', 'casefold', 'cat', 'center', 'contains', 'count', 'decode', 'encode', 'endswith', 'extract', 'extractall', 'find', 'findall', 'fullmatch', 'get', 'get_dummies', 'index', 'isalnum', 'isalpha', 'isdecimal', 'isdigit', 'islower', 'isnumeric', 'isspace', 'istitle', 'isupper', 'join', 'len', 'ljust', 'lower', 'lstrip', 'match', 'normalize', 'pad', 'partition', 'removeprefix', 'removesuffix', 'rep

In [204]:
# Rewrite column headers to strip off leading text
data.columns = data.columns.str.strip("gdpPercap_")
print(data.columns)

Index(['1952', '1957', '1962', '1967', '1972', '1977', '1982', '1987', '1992',
       '1997', '2002', '2007'],
      dtype='object')


In [206]:
data.loc["Albania", "1952"]

1601.056136

In [210]:
# Italy through poland from 1962-1972
subset = data.loc["Italy":"Poland","1962":"1972"]

In [212]:
subset

1962          1967          1972
country                                              
Italy         8243.582340  10022.401310  12269.273780
Montenegro    4649.593785   5907.850937   7778.414017
Netherlands  12790.849560  15363.251360  18794.745670
Norway       13450.401510  16361.876470  18965.055510
Poland        5338.752143   6557.152776   8006.506993

In [218]:
# Get all of the variables for aubset of rows 
data.loc["Italy":"Poland",:]

1952          1957          1962          1967  \
country                                                               
Italy         4931.404155   6248.656232   8243.582340  10022.401310   
Montenegro    2647.585601   3682.259903   4649.593785   5907.850937   
Netherlands   8941.571858  11276.193440  12790.849560  15363.251360   
Norway       10095.421720  11653.973040  13450.401510  16361.876470   
Poland        4029.329699   4734.253019   5338.752143   6557.152776   

                     1972          1977          1982          1987  \
country                                                               
Italy        12269.273780  14255.984750  16537.483500  19207.234820   
Montenegro    7778.414017   9595.929905  11222.587620  11732.510170   
Netherlands  18794.745670  21209.059200  21399.460460  23651.323610   
Norway       18965.055510  23311.349390  26298.635310  31540.974800   
Poland        8006.506993   9508.141454   8451.531004   9082.351172   

                     1992          1997          2002          2007  
country                                                              
Italy        22013.644860  24675.024460  27968.098170  28569.719700  
Montenegro    7003.339037   6465.613349   6557.194282   9253.896111  
Netherlands  26790.949610  30246.130630  33724.757780  36797.933320  
Norway       33965.661150  41283.164330  44683.975250  49357.190170  
Poland        7738.881247  10159.583680  12002.239080  15389.924680

In [220]:
subset.describe()

1962          1967          1972
count      5.000000      5.000000      5.000000
mean    8894.635868  10842.506571  13162.799194
std     4093.410673   4855.106424   5517.298708
min     4649.593785   5907.850937   7778.414017
25%     5338.752143   6557.152776   8006.506993
50%     8243.582340  10022.401310  12269.273780
75%    12790.849560  15363.251360  18794.745670
max    13450.401510  16361.876470  18965.055510

In [224]:
subset.max()

1962    13450.40151
1967    16361.87647
1972    18965.05551
dtype: float64

## Challenge
1. Calculate subset max() and assign the result to a variable. What kind of thing is it?
2. What is the maximum value of the new thing?
3. Can you calculate the max value of the new thing in one step?

In [233]:
sm= subset.max()
print(sm)

1962    13450.40151
1967    16361.87647
1972    18965.05551
dtype: float64


In [241]:
print(type(subset))
print(type(sm))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [237]:
max_sm=max(sm)
print(max_sm)

18965.05551


In [245]:
# Do it in one step
subset.max().max()

18965.05551

In [253]:
# Other solution
print("Default max")
print(subset.max())
print("Max along axis 0")
print(subset.max(axis=0))
print("Max along axis 1")
print(subset.max(axis=1))

Default max
1962    13450.40151
1967    16361.87647
1972    18965.05551
dtype: float64
Max along axis 0
1962    13450.40151
1967    16361.87647
1972    18965.05551
dtype: float64
Max along axis 1
country
Italy          12269.273780
Montenegro      7778.414017
Netherlands    18794.745670
Norway         18965.055510
Poland          8006.506993
dtype: float64


In [255]:
# Get max for overall data frame (not row or column) 
subset.max(axis=None)

18965.05551

# Filter Data by Criteria

In [258]:
subset

1962          1967          1972
country                                              
Italy         8243.582340  10022.401310  12269.273780
Montenegro    4649.593785   5907.850937   7778.414017
Netherlands  12790.849560  15363.251360  18794.745670
Norway       13450.401510  16361.876470  18965.055510
Poland        5338.752143   6557.152776   8006.506993

In [260]:
# Get GDP's greater than 10,000
subset> 10000

1962   1967   1972
country                         
Italy        False   True   True
Montenegro   False  False  False
Netherlands   True   True   True
Norway        True   True   True
Poland       False  False  False

In [262]:
# Filter data fram by criterion
df = subset[subset > 10000]
df

1962         1967         1972
country                                           
Italy                NaN  10022.40131  12269.27378
Montenegro           NaN          NaN          NaN
Netherlands  12790.84956  15363.25136  18794.74567
Norway       13450.40151  16361.87647  18965.05551
Poland               NaN          NaN          NaN

In [266]:
# Get everything above the median
subset[subset > subset.median(axis=None)]

1962         1967         1972
country                                           
Italy                NaN          NaN  12269.27378
Montenegro           NaN          NaN          NaN
Netherlands  12790.84956  15363.25136  18794.74567
Norway       13450.40151  16361.87647  18965.05551
Poland               NaN          NaN          NaN

In [268]:
df

1962         1967         1972
country                                           
Italy                NaN  10022.40131  12269.27378
Montenegro           NaN          NaN          NaN
Netherlands  12790.84956  15363.25136  18794.74567
Norway       13450.40151  16361.87647  18965.05551
Poland               NaN          NaN          NaN

# Working with Missing Data

In [275]:
# Missing Data is ignored by default
print("Column means")
print(df.mean())

print("Row means")
print(df.mean(axis=1))


Column means
1962    13120.625535
1967    13915.843047
1972    16676.358320
dtype: float64
Row means
country
Italy          11145.837545
Montenegro              NaN
Netherlands    15649.615530
Norway         16259.111163
Poland                  NaN
dtype: float64


In [277]:
# Check for missing values
df.isna()
# True --> this number is missing

1962   1967   1972
country                         
Italy         True  False  False
Montenegro    True   True   True
Netherlands  False  False  False
Norway       False  False  False
Poland        True   True   True

In [279]:
# Count our missing values 
# Missing by row
df.isna().sum()

1962    3
1967    2
1972    2
dtype: int64

In [283]:
# Check total missing values
df.isna().sum().sum()

7

In [287]:
# Drop missing values 
df.dropna()

1962         1967         1972
country                                           
Netherlands  12790.84956  15363.25136  18794.74567
Norway       13450.40151  16361.87647  18965.05551

In [289]:
# Replace missing values with a fixed value
df_fixed = df.fillna(99)
print(df_fixed)

                    1962         1967         1972
country                                           
Italy           99.00000  10022.40131  12269.27378
Montenegro      99.00000     99.00000     99.00000
Netherlands  12790.84956  15363.25136  18794.74567
Norway       13450.40151  16361.87647  18965.05551
Poland          99.00000     99.00000     99.00000


In [291]:
# Replace missing values with interpolated data
df_interpolated=df.interpolate()
print(df_interpolated)

                    1962          1967          1972
country                                             
Italy                NaN  10022.401310  12269.273780
Montenegro           NaN  12692.826335  15532.009725
Netherlands  12790.84956  15363.251360  18794.745670
Norway       13450.40151  16361.876470  18965.055510
Poland       13450.40151  16361.876470  18965.055510


## Challenge: The perils of missing data
1. Create an array of random numbers matching the "data" dataframe

random_filter = np.random.ran(30,12) * data.max(axis=None)

2. Create a new data frame that filters out all values lower than the random numbers
3. Interpolate new values for the missing data in the new data frame. How accurate is it?

In [368]:
random_filter=np.random.rand(30,12)*data.max(axis=None)
dff= data[data>random_filter]
dff_interpolated=dff.interpolate()
#print(np.std(data,axis=0))
#print(np.std(dff,axis=0))
#print(np.std((data,dff),axis=None))

In [388]:
# His answer
new_data = data[data > random_filter]
new_data_interpolated=new_data.interpolate()
data.describe()

1952          1957          1962          1967          1972  \
count     30.000000     30.000000     30.000000     30.000000     30.000000   
mean    5661.057435   6963.012816   8365.486814  10143.823757  12479.575246   
std     3114.060493   3677.950146   4199.193906   4724.983889   5509.691411   
min      973.533195   1353.989176   1709.683679   2172.352423   2860.169750   
25%     3241.132406   4394.874315   5373.536612   6657.939047   9057.708094   
50%     5142.469716   6066.721495   7515.733737   9366.067033  12326.379990   
75%     7236.794919   9597.220820  10931.085348  13277.182058  16523.017127   
max    14734.232750  17909.489730  20431.092700  22966.144320  27195.113040   

               1977          1982          1987          1992          1997  \
count     30.000000     30.000000     30.000000     30.000000     30.000000   
mean   14283.979110  15617.896551  17214.310727  17061.568084  19076.781802   
std     5874.464896   6453.234827   7482.957960   9109.804361  10065.457716   
min     3528.481305   3630.880722   3738.932735   2497.437901   3193.054604   
25%    10360.030300  11449.870115  12274.570680   8667.113214   9946.599306   
50%    14225.754515  15322.824720  16215.485895  17550.155945  19596.498550   
75%    19052.412163  20901.729730  23321.587723  25034.243045  27189.530312   
max    26982.290520  28397.715120  31540.974800  33965.661150  41283.164330   

               2002          2007  
count     30.000000     30.000000  
mean   21711.732422  25054.481636  
std    11197.355517  11800.339811  
min     4604.211737   5937.029526  
25%    11721.851483  14811.898210  
50%    23674.863230  28054.065790  
75%    30373.363307  33817.962533  
max    44683.975250  49357.190170

In [390]:
new_data_interpolated.describe()

1952          1957          1962          1967          1972  \
count    28.000000     21.000000     20.000000     26.000000     29.000000   
mean   6375.990805   7679.843653   7193.788490   8329.236616  14188.051001   
std    1130.586922   2062.477428   1572.467405   3690.339776   3426.919830   
min    5074.659104   3774.571743   6631.597314   5577.002800   6597.494398   
25%    5194.050755   6275.112309   6631.597314   5883.454047  12269.273780   
50%    6268.575617   7491.449728   6631.597314   6189.905295  14335.385268   
75%    7331.456695   8780.309214   6631.597314  10439.208357  16854.308505   
max    8343.105127  11283.177950  12902.462910  15258.296970  18965.055510   

               1977          1982          1987          1992          1997  \
count     29.000000     23.000000     29.000000     28.000000     28.000000   
mean   18758.456143  18508.209773  17873.960622  24742.867992  23478.042775   
std     4260.470680   5646.316982   5491.477991   6144.875423   7916.315160   
min     9508.141454   4241.356344   9082.351172  14297.021220   6465.613349   
25%    16955.473610  16663.263468  13901.125355  18483.274626  16811.031166   
50%    19678.577428  20830.065519  16310.443400  25406.434050  26413.895810   
75%    19733.678995  21196.105124  22525.563080  30468.618347  28459.018350   
max    26982.290520  28397.715120  31540.974800  33965.661150  41283.164330   

               2002          2007  
count     30.000000     29.000000  
mean   26208.405175  34925.904724  
std    10043.287590   5702.764488  
min     4604.211737  18008.944440  
25%    21703.882435  33203.261280  
50%    30223.701977  33692.605080  
75%    31411.490642  36643.647287  
max    44683.975250  49357.190170

# Sorting and Grouping Data

In [402]:
# Z score all of the GDP data points
#ddof - degrees of freedom
# data.values is a numpy precursor
z = (data - data.mean(axis=None))/data.values.std(ddof=1)
#z

In [406]:
# Get mean z score for each county
mean_z=z.mean(axis=1)
mean_z.sort_values()

country
Albania                  -1.198702
Bosnia and Herzegovina   -1.174179
Turkey                   -1.068925
Bulgaria                 -0.864269
Montenegro               -0.776189
Romania                  -0.766343
Poland                   -0.647011
Serbia                   -0.552037
Croatia                  -0.549187
Slovak Republic          -0.433335
Hungary                  -0.382813
Portugal                 -0.333010
Czech Republic           -0.058733
Greece                   -0.053493
Spain                    -0.046995
Slovenia                 -0.042211
Ireland                   0.137798
Italy                     0.189812
Finland                   0.321131
France                    0.466488
United Kingdom            0.524948
Belgium                   0.580562
Sweden                    0.585091
Austria                   0.635201
Iceland                   0.647975
Germany                   0.650676
Denmark                   0.769875
Netherlands               0.778109
Norway      

In [410]:
bool_z=mean_z >0
bool_z

country
Albania                   False
Austria                    True
Belgium                    True
Bosnia and Herzegovina    False
Bulgaria                  False
Croatia                   False
Czech Republic            False
Denmark                    True
Finland                    True
France                     True
Germany                    True
Greece                    False
Hungary                   False
Iceland                    True
Ireland                    True
Italy                      True
Montenegro                False
Netherlands                True
Norway                     True
Poland                    False
Portugal                  False
Romania                   False
Serbia                    False
Slovak Republic           False
Slovenia                  False
Spain                     False
Sweden                     True
Switzerland                True
Turkey                    False
United Kingdom             True
dtype: bool

In [420]:
# Add new columns to data frame
data["mean_z"]= mean_z
data["wealthy"]=bool_z
data.head(3)

1952         1957          1962          1967          1972  \
country                                                                       
Albania  1601.056136  1942.284244   2312.888958   2760.196931   3313.422188   
Austria  6137.076492  8842.598030  10750.721110  12834.602400  16661.625600   
Belgium  8343.105127  9714.960623  10991.206760  13149.041190  16672.143560   

                1977          1982          1987          1992          1997  \
country                                                                        
Albania   3533.00391   3630.880722   3738.932735   2497.437901   3193.054604   
Austria  19749.42230  21597.083620  23687.826070  27042.018680  29095.920660   
Belgium  19117.97448  20979.845890  22525.563080  25575.570690  27561.196630   

                 2002          2007    mean_z  welathy  wealthy  
country                                                          
Albania   4604.211737   5937.029526 -1.198702    False    False  
Austria  32417.607690  36126.492700  0.635201     True     True  
Belgium  30485.883750  33692.605080  0.580562     True     True

In [422]:
# Get descriptive statistics for groups
data.groupby("wealthy").mean()

1952         1957          1962          1967          1972  \
wealthy                                                                       
False    3460.797562  4356.915102   5381.266911   6789.774524   8589.054224   
True     8175.640146  9941.410203  11776.023847  13977.022880  16925.884987   

                 1977          1982          1987          1992          1997  \
wealthy                                                                         
False    10123.062167  10999.519354  11657.755578   9814.771634  11010.972268   
True     19039.312758  20896.041919  23564.659468  25343.621170  28294.849840   

                 2002          2007    mean_z  welathy  
wealthy                                                 
False    12762.305369  15908.649976 -0.559215      0.0  
True     31939.649055  35506.860676  0.639102      1.0

In [426]:
# Get descriptive statistics for each group
data.groupby("wealthy").describe()

1952                                                      \
        count         mean          std          min          25%   
wealthy                                                             
False    16.0  3460.797562  1472.093863   973.533195  2596.760863   
True     14.0  8175.640146  2522.755539  4931.404155  6575.841635   

                                                1957               ...  \
                 50%          75%          max count         mean  ...   
wealthy                                                            ...   
False    3337.651627  4075.757709   6876.14025  16.0  4356.915102  ...   
True     7805.396778  9504.681898  14734.23275  14.0  9941.410203  ...   

                 2007              mean_z                                \
                  75%          max  count      mean       std       min   
wealthy                                                                   
False    21090.562955  28821.06370   16.0 -0.559215  0.397648 -1.198702   
True     36643.647287  49357.19017   14.0  0.639102  0.350282  0.137798   

                                                 
              25%       50%       75%       max  
wealthy                                          
False   -0.798209 -0.550612 -0.264441 -0.042211  
True     0.481103  0.610146  0.740075  1.347362  

[2 rows x 104 columns]

In [430]:
# Write output to save chnages made
data.to_csv("europe_normed.csv")